def test_split():
    date_str = "2026-01-08"
    
    # Simulate content generated by main.py
    holdings_section = f"\n# 📊 持仓分析日报 ({date_str})\n\nSome content for holdings..."
    candidates_section = f"\n# 🎯 今日选股参考 ({date_str}) (AI精选)\n\nSome content for candidates..."
    
    full_md = "MARKET_SECTION\n" + holdings_section + candidates_section
    
    print(f"Original MD:\n{full_md}\n")
    
    # Simulate web_server.py logic
    parts = {"market": "", "holdings": "", "candidates": ""}
    current_md = full_md
    
    if "# 🎯 今日选股参考" in current_md:
        pre, candidates = current_md.split("# 🎯 今日选股参考", 1)
        parts["candidates"] = "# 🎯 今日选股参考" + candidates
        current_md = pre
        
    if "# 📊 持仓分析日报" in current_md:
        pre, holdings = current_md.split("# 📊 持仓分析日报", 1)
        parts["holdings"] = "# 📊 持仓分析日报" + holdings
        current_md = pre
        
    parts["market"] = current_md
    
    print("--- Parsed Parts ---")
    print(f"Market: {parts['market'].strip()}")
    print(f"Holdings Header: {parts['holdings'].splitlines()[0]}")
    print(f"Candidates Header: {parts['candidates'].splitlines()[0]}")

if __name__ == "__main__":
    test_split()